STARTWIN.EXE:                       STARTWIN.OBJ
        LINK386 @<<
STARTWIN
STARTWIN
STARTWIN
OS2386
STARTWIN
<<

STARTWIN.OBJ:                       STARTWIN.C
        ICC -C+ -Kb+ -Ss+ STARTWIN.C
