ALL:    STHREAD.EXE FTHREAD.EXE

STHREAD.EXE:                     STHREAD.OBJ
        LINK386 @<<
STHREAD
STHREAD
STHREAD
OS2386
STHREAD
<<

STHREAD.OBJ:          STHREAD.C SFTHREAD.MAK
        ICC -C+ -Gm+ -Kb+ -Sm -Ss+ STHREAD.C

FTHREAD.EXE:                     FTHREAD.OBJ
        LINK386 @<<
FTHREAD
FTHREAD
FTHREAD
OS2386
FTHREAD
<<

FTHREAD.OBJ:          FTHREAD.C SFTHREAD.MAK
        ICC -C+ -Gm+ -Kb+ -Sm -Ss+ FTHREAD.C
